#pragma once
// repurpose assembly using low coverage SNPs from a subspecies to
// modify a reference assembly
// Useful when attempting to discover differential haplotype regions
// in F4's relative to unassembled founders
//
const int cMaxSNPChromNames = 500000;		// can only handle a max of this many chromosome names - memory is statically allocated
const int cAllocNumSNPs = 10000000;			// allocate for SNPs in this sized blocks
const int cAlignNumSSNPfields = 23;			// if generated by 'kit4b kalign' then there will be this many CSV fields
const int cAlignNumSSNPXfields = 23 + (3 * 65);	// if generated by 'kit4b kalign' for all 3 read counts frame shifts (3*4^3) + fixed reference frame shifts (3*3) then there will be this many CSV fields
const int cSSNPMarkerNumFields = 4 + 9;		// if generated by 'kit4b snpmarkers' then there will be a minimum of this number of CSVfields
const int cAllocAssembFastaMem = 0x03fffffff;		// allocating memory buffering for assembly sequences in chunks of this size 

const uint32_t cDfltMinSiteCoverage = 10;		// must be at least this number of covering bases at SNP site to be accepted
const double cDfltMinAlleleProp = 0.5;			// major allele must be at least this proportion of all alleles (incl ref base) at SNP site to be accepted
const double cDfltPValueThres = 0.05;			// and PValue must be <= this threshold

#pragma pack(1)
typedef enum TAG_eRPPMode{
	eRPMdefault,		// default, and currently only processing mode
	eRPMplaceholder	// placeholder
} etRPPMode;

typedef struct TAG_sSNPSSite
{
	uint32_t ChromID;		// SNP is on the chromosome
	uint32_t Loci;			// at this loci
	etSeqBase RefBase;		// reference assembly base
	etSeqBase AlleleBase;	// allignment has this major allelic base called
} tsSNPSite;

typedef struct TAG_sChromSites
{
	uint32_t ChromID;		// SNPs are on this chromosome
	uint32_t SNPSiteIdx;	// index into m_pSNPSites for 1st site on this chromosome
	uint32_t NumSNPSites;	// number of SNP sites on this chromosome
} tsChromSites;

#pragma pack()

class CRepAssemb
{
	char m_szTargAssemblyName[cMaxDatasetSpeciesChrom + 1]; // alignments were against this targeted assembly
	char m_szCurChrom[cMaxDatasetSpeciesChrom+1];	  // processing SNP on this chromosome
	uint32_t m_CurChromID;						// current chromosome identifier

	int m_LAChromNameID;						// last accessed chromosome identifier from call to AddChrom()
	int m_NumChromNames;						// number of chromosome names currently in m_szChromNames
	int m_NxtszChromIdx;						// current concatenated (names separated by '\0') of all chromosome names in m_szChromNames
	int m_NumChromSites;						// number of chromosomes with at least one accepted SNP site
	char m_szChromNames[cMaxSNPChromNames * (cMaxDatasetSpeciesChrom/2)];	// used to hold concatenated chromosome names, each separated by '\0'
	uint32_t m_szChromIdx[cMaxSNPChromNames];		// array of indexes into m_szChromNames giving the starts of each chromosome name
	tsChromSites m_ChromSites[cMaxSNPChromNames];	// chromosome sites

	CCSVFile* m_pCSV;							// used to load SNP calls

	uint32_t m_MinCoverage;						// must be at least this number of covering bases at SNP site to be accepted
	double m_MinAlleleProp;						// major allele must be at least this proportion of all alleles (incl ref base) at SNP site to be accepted
	double m_PValueThres;						// and PValue must be <= this threshold

	size_t m_SeqBuffIdx;						// currently buffering this many bases
	size_t m_AllocSeqBuffMem;					// m_pSeqBuffer allocated to this size (realloc'd if required)
	uint8_t *m_pSeqBuffer;						// allocated to buffer input/output fasta sequences 
	int m_hInFile;								// input assembly file handle
	int m_hOutFile;								// output assembly file handle

	uint32_t m_NumSNPSites;						// number of SNP sites accepted
	uint32_t m_NumAllocdSNPSites;				// number of SNP sites currently allocated
	size_t m_AllocdSNPSitesMem;					// allocd memory size for holding m_NumAllocdSNPSites
	tsSNPSite *m_pSNPSites;						// pts to allocd SNP sites
					

	int		// returned chrom identifier, < 1 if unable to accept this chromosome name
		AddChrom(char* pszChrom); // associate unique identifier with this chromosome name

	char*	// returns chromosome name associated with 
		LocateChrom(int ChromID); // chromosome identifier

	tsChromSites * // returned ptr
		LocateChromSites(char* pszChrom);	// sites are to be those on this chromosome

	int						// returned total number of SNPs parsed and accepted
		LoadKalignSNPs(char *pszSNPFile);	// load and parse kalign generated SNPs


	int									// number of bases replaced
		ReplaceBases(char *pszChrom,	// chromosome name
			 uint32_t SeqLen,			// max of this number of bases in sequence
			 char *pszSeq);				// sequence

	CStats m_Stats;								// basic statistics

	static int SortSNPChromLoci(const void* arg1, const void* arg2);

public:
	CRepAssemb(void);			// constructor

	~CRepAssemb(void);			// destructor
	
	void Reset(void);				// resets instance state back to that immediately following instantiation

	int ProccessAssembly(char *pszSNPFile,	// input kalign generated SNPs file
				char* pszInFile,		// input fasta assembly file
				char* pszOutFile);		// output to this fasta assembly file

};

